services:
  app:
    image: todo-front-dev
    build:
      context: ./todo-frontend 
      dockerfile: dev.Dockerfile
    environment:
      - VITE_BACKEND_URL=/api
    volumes:
      - ./todo-frontend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: todo-front-dev

  server:
    image: todo-back-dev
    build:
      context: ./todo-backend 
      dockerfile: dev.Dockerfile
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/the_database?authSource=admin
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./todo-backend:/usr/src/app 
      - /usr/src/app/node_modules
    container_name: todo-back-dev

  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-dev
    depends_on:
      - app
      - server

  debug-helper:
    image: busybox
  
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data

volumes:
  mongo_data: